### ISSUE TITLE
The script cannot parse the red text correctly

### ISSUE THREAD

**Issue by lawvs** [kcwikizh/kcQuests#6]
```
'''{{Red|（不含空母系）}}'''
```
![telegram-cloud-photo-size-5-6082298282916295728-y](https://user-images.githubusercontent.com/18554747/224553929-29961a55-29de-4e8c-aa20-52e20e53914f.jpg)

![telegram-cloud-photo-size-5-6082298282916295727-x](https://user-images.githubusercontent.com/18554747/224553984-681d42ef-c54b-4b55-9ce8-66cae06158e7.jpg)

https://github.com/kcwikizh/kcQuests/blob/70f54c865214b07a980068be223dd19d610ed800/rs/0-16.txt#L8

https://github.com/kcwikizh/kcQuests/blob/70f54c865214b07a980068be223dd19d610ed800/fineJson/0-16.json#L1

**Comment by callofblood** [comment]
![image](https://user-images.githubusercontent.com/70617760/224591904-f070afda-ee5c-4b63-8f91-5fa7be3d351c.png)
done
